/* Human Review chrome behavior, backed only by Subspace Annotation + feedback-only Relay Result. */
const $ = (id) => document.getElementById(id);
const state = { comments: [], quote: '', draftRange: null, savedRanges: [], active: null, identityKey: 'subspace-reviewer-name-v1', themeKey: 'subspace-chrome-theme-v1' };
const esc = (value) => { const node = document.createElement('div'); node.textContent = value; return node.innerHTML; };
const identity = (name) => { const slug = name.trim().toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9._@-]/g, ''); return slug ? `person:${slug}` : ''; };
const currentIdentity = () => identity(localStorage.getItem(state.identityKey) || '');
function toast(message) { const el = document.createElement('div'); el.className = 'toast'; el.textContent = message; document.body.append(el); setTimeout(() => el.remove(), 3200); }
function applyTheme(theme) { document.documentElement.dataset.theme = theme; localStorage.setItem(state.themeKey, theme); $('theme').textContent = theme === 'dark' ? '☀' : '☾'; }
function toggleTheme() { applyTheme(document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark'); }
function renderIdentity() { const name = localStorage.getItem(state.identityKey) || 'Not set'; $('identity-chip').innerHTML = `<i class="identity-dot"></i><div><div class="identity-name">${esc(name)}</div><div class="identity-portable">${esc(currentIdentity() || 'person:<name>')}</div></div><button class="change" id="identity-edit">Change</button>`; $('identity-edit').onclick = showIdentity; }
function showIdentity() { $('identity-cover').hidden = false; $('identity-name').value = localStorage.getItem(state.identityKey) || ''; $('identity-name').focus(); }
function setIdentity(name) { if (!identity(name)) { $('identity-preview').textContent = 'Enter a name using letters or numbers.'; return; } localStorage.setItem(state.identityKey, name.trim()); $('identity-cover').hidden = true; renderIdentity(); }
function clearDraft() { CSS.highlights?.delete('subspace-draft'); state.draftRange = null; }
function paintSaved() { if (!CSS.highlights) return; CSS.highlights.delete('subspace-saved'); if (state.savedRanges.length) CSS.highlights.set('subspace-saved', new Highlight(...state.savedRanges)); }
function closeCompose() { clearDraft(); $('compose').hidden = true; $('mobile-compose').hidden = true; $('mobile-action').hidden = true; }
function selectionInArtifact() { const s = getSelection(); const range = s.rangeCount ? s.getRangeAt(0).cloneRange() : null; return range && s.toString().trim() && $('artifact').contains(range.commonAncestorContainer) ? { range, quote: s.toString().trim() } : null; }
function openCompose() { const picked = selectionInArtifact(); if (!picked) return; state.quote = picked.quote; state.draftRange = picked.range; CSS.highlights?.set('subspace-draft', new Highlight(picked.range)); $('composeKind').textContent = 'Selection'; if (matchMedia('(max-width:800px)').matches) { $('mobileQuote').textContent = state.quote; $('mobile-compose').hidden = false; } else { $('composeQuote').textContent = state.quote; $('compose').hidden = false; } }
function activateComment(index, scroll) { state.active = index; render(); if (scroll) state.savedRanges[index]?.startContainer?.parentElement?.scrollIntoView({ behavior: 'smooth', block: 'center' }); }
function deleteComment(index) { state.comments.splice(index, 1); state.savedRanges.splice(index, 1); state.active = null; paintSaved(); render(); }
function editComment(card, body, index) { if (card.querySelector('textarea')) return; const input = document.createElement('textarea'); input.className = 'body-edit'; input.rows = 3; input.value = state.comments[index].feedback; const finish = (commit) => { const text = input.value.trim(); if (commit && text) state.comments[index].feedback = text; render(); }; input.onkeydown = (event) => { event.stopPropagation(); if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); finish(true); } if (event.key === 'Escape') { event.preventDefault(); finish(false); } }; input.onblur = () => finish(true); input.onclick = (event) => event.stopPropagation(); body.replaceWith(input); input.focus(); }
function render() { $('count').textContent = state.comments.length; $('empty').hidden = !!state.comments.length || !$('compose').hidden; $('cards').innerHTML = state.comments.map((comment, index) => `<div class="comment ${state.active === index ? 'active' : ''}" data-index="${index}"><div class="comment-head"><span class="who">${esc(comment.by)} · just now</span><button class="jump" data-jump="${index}">Jump to</button><button class="remove" data-remove="${index}" aria-label="Delete comment">✕</button></div><p class="quote">${esc(comment.quote)}</p><p class="body" data-body="${index}">${esc(comment.feedback)}</p></div>`).join(''); document.querySelectorAll('.comment').forEach((card) => card.onclick = () => activateComment(+card.dataset.index, false)); document.querySelectorAll('.jump').forEach((button) => button.onclick = (event) => { event.stopPropagation(); activateComment(+button.dataset.jump, true); }); document.querySelectorAll('.remove').forEach((button) => button.onclick = (event) => { event.stopPropagation(); deleteComment(+button.dataset.remove); }); document.querySelectorAll('.body').forEach((body) => body.onclick = (event) => { event.stopPropagation(); editComment(body.closest('.comment'), body, +body.dataset.body); }); const ready = state.comments.length || $('note').value.trim(); $('send').disabled = !ready; $('send').textContent = ready ? `Send ${state.comments.length || 'note'} to Relay` : 'Nothing to send yet'; }
function commit(text, kind = "comment") { if (!text.trim() || !state.draftRange) return; state.comments.push({ kind, quote: state.quote, feedback: text.trim(), by: currentIdentity() }); state.savedRanges.push(state.draftRange); clearDraft(); paintSaved(); $('composeText').value = ''; $('mobileText').value = ''; getSelection().removeAllRanges(); closeCompose(); state.active = state.comments.length - 1; render(); }
async function submit() { const reviewer = currentIdentity(); if (!reviewer) return showIdentity(); $('status').textContent = 'Submitting…'; try { const response = await fetch('/api/submit', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ reviewer, comments: state.comments, overall_note: $('note').value.trim() }) }); const body = await response.json(); if (!response.ok) throw Error(body.error); $('status').textContent = `Submitted Result ${body.result_id}`; $('agentLine').hidden = false; $('agentText').textContent = 'Feedback submitted to Relay'; } catch (error) { $('status').textContent = `Error: ${error.message}`; } }
async function showTeamFeedback() { const target = $('team'); target.hidden = false; target.textContent = 'Loading…'; try { const response = await fetch('/api/shared-feedback'); const body = await response.json(); if (!response.ok) throw Error(body.error); target.innerHTML = (body.annotations || []).map((annotation) => `<div class="comment"><span class="who">${esc(annotation.by)}</span><p class="quote">${esc(annotation.quote || 'Overall note')}</p><p class="body">${esc(annotation.body)}</p></div>`).join('') || '<div class="empty">No team feedback yet</div>'; } catch (error) { target.textContent = error.message; } }
function openDiagram(svg) { $('diagram-stage').innerHTML = svg; $('diagram-lightbox').hidden = false; }
window.openDiagram = openDiagram;
function boot() { $('handle').onclick = () => document.body.classList.toggle('collapsed'); $('theme').onclick = toggleTheme; $('shared').onclick = showTeamFeedback; $('identity-confirm').onclick = () => setIdentity($('identity-name').value); $('composeAdd').onclick = () => commit($('composeText').value); $('composeSuggest').onclick = () => commit($('composeText').value, "suggestion"); $('composeCancel').onclick = closeCompose; $('mobileAdd').onclick = () => commit($('mobileText').value); $('mobileCancel').onclick = closeCompose; $('stage').addEventListener('mouseup', () => setTimeout(openCompose)); $('stage').addEventListener('touchend', () => setTimeout(() => { if (selectionInArtifact()) $('mobile-action').hidden = false; }, 160)); $('mobile-action').onclick = openCompose; $('note').oninput = render; $('send').onclick = submit; document.addEventListener('keydown', (event) => { if (event.key === 'Escape') closeCompose(); if ((event.metaKey || event.ctrlKey) && event.key === 'Enter' && !$('send').disabled) submit(); }); $('diagram-lightbox').onclick = (event) => { if (event.target === $('diagram-lightbox')) $('diagram-lightbox').hidden = true; }; applyTheme(localStorage.getItem(state.themeKey) || 'light'); localStorage.getItem(state.identityKey) ? renderIdentity() : showIdentity(); render(); }
window.subspaceChrome = { boot, render, openCompose, closeCompose, state };
